[workspace]
resolver = "2"
members = ["crates/bin", "crates/state"]
default-members = ["crates/bin"]

[workspace.dependencies]
state = { path = "crates/state" }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
