[workspace]
resolver = "2"
members = [ "crates/ble", "crates/rx", "crates/state"]

[workspace.dependencies]
state = { path = "crates/state" }
ble = { path = "crates/ble" }

log = { version = "0.4.28", default-features = false }
esp-hal = { version = "1.0.0", default-features = false }
esp-println = { version = "0.16.1", default-features = false }
esp-radio = { version = "0.17.0", default-features = false }
esp-alloc = { version = "0.9.0", default-features = false }
esp-rtos = { version = "0.2.0", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
embedded-io = { version = "0.7.1", default-features = false }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
