[package]
name = "rx"
version = "0.1.0"
edition = "2024"

[dependencies]
ble = { workspace = true }
esp-alloc = { workspace = true, features = ["esp32c3"] }
esp-hal = { workspace = true, features = ["esp32c3", "rt", "log-04", "unstable"] }
esp-println = { workspace = true, features = ["esp32c3", "log-04", "auto" ] }
esp-radio = { workspace = true, features = ["esp32c3", "log-04", "ble", "unstable"] }
esp-rtos = { workspace = true, features = ["esp32c3", "log-04", "esp-radio", "esp-alloc"] }
log = { workspace = true }
